default: &default
  adapter: postgresql
  encoding: utf8
  pool: 100
  timeout: 5000
  username: youleshu
  password: 123456

development:
  <<: *default
  database: postal_book 

test:
  <<: *default
  database: postal_book_test

production:
  <<: *default
  database: postal_book_production
