default: &default
  adapter: mysql2
  encoding: utf8
  pool: 100
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: postal_book 

test:
  <<: *default
  database: postal_book_test

production:
  <<: *default
  database: postal_book_production
